### ISSUE TITLE
Tidy up, remove hacks, FIXME, TODO

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltIndicator#260]
To deduIplicate the ICTR and PCTR into XCTR I did a few hacks that need to be removed ASAP. That will make it easier to re-write PSTR and ISTR reusing the same code.

Some things to consider:

DRY

- [ ] Reuse the idea of `ptype_at_company_level()`
- [ ] Reuse `check_crucial_names()`
- [ ] Reuse `check_*()` in general

**Comment by maurolepore** [comment]
This is vague and stale.
