### ISSUE TITLE
XSTR overview ticket - last changes before delivery

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltIndicator#401]
Adapt the file that fixes XSTR outputs (https://github.com/2DegreesInvesting/tiltIndicator/pull/397) to also account for the following issues. Every modification that's applicable and sensical to both ISTR & PSTR level should be applied to both files.

XSTR

- [x] 1. (https://github.com/2DegreesInvesting/tiltIndicator/pull/397/commits/460b1acd9c3cb1ea92ae66112b65adbec5589b2c) `pstr_product_level_results` & `istr_product_level_results`: Delete all rows with NAs in risk_category, except for companies_id that only have NA in risk category. In latter case, keep companies_id with one row but make all other columns NA. Then, we should have always 1, 2 or 4 rows per `companies_id `- `clustered `combination, at least in pstr. See Mauro's related reprex [here](https://gist.github.com/maurolepore/84b3aa6581d89966d4d5de817cbf35c6). Ticket with suggested solution: [In PSTR, delete NA rows from pstr_product_level results#402](https://github.com/2DegreesInvesting/tiltIndicator/issues/402)
- [x] 2. (6408efb) `istr_company_level_results` & `pstr_company_level_results`: Remove `companies_id` with ";" either of the scenario columns in `pstr_companies `input file. This case should already be captured by the removal of `NA `rows above, but as the problem origins from another source, I list it separately. Respective ticket identifying those cases can be found here: Identify number of companies which contain semicolon in either of the four scenario columns in pstr_companies #405
- [x] 3. (0c96407) `pstr_company_level_results` & `istr_company_level_results`: Delete results for `companies_id` where we have differing product- and company-level results because of duplicated scenarios in the product-level results.  Refer to [this reprex ](https://gist.github.com/maurolepore/84b3aa6581d89966d4d5de817cbf35c6) where we deleted certain rows in `pstr_product_level ` that now lead to misaligned results between product- and company-level.  --> ticket showing how to remove the respective results: [In PSTR, assess whether results for product- and company-level results add up for products with former duplicated scenario rows.#403](https://github.com/2DegreesInvesting/tiltIndicator/issues/403)

ISTR

- [x] 4. `istr_company_level`: Exclude results for 287 `companies_id ` that are missing because of error in chunk. Note: we should still display the missing `companies_id `with one row NAs in all columns. We can work on a solution for this in the future: [In ISTR, solve problem with missing chunk of companies_id#406](https://github.com/2DegreesInvesting/tiltIndicator/issues/406)

![Image](https://github.com/2DegreesInvesting/tiltIndicator/assets/88719608/f44344f9-69ba-478c-84f1-f66774fa170e)

Let's discuss and conquer together tomorrow morning in the office @AnneSchoenauer & @kalashsinghal.

Link to data prep script so far [here](https://github.com/2DegreesInvesting/tiltIndicator/blob/396_Fix-xstr-outputs/data-raw/396_fix-xstr-outputs.md)

cc' @maurolepore

**Comment by kalashsinghal** [comment]
@Tilmon You can just use this command for removing NA rows from output file for the first case: `pstr_prod_level |> filter(!is.na(risk_category))`
